let us create a simpler model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv('./mydata.csv')
dataset.head()

,date,clock,stadium,class,attendance,Home Team,Goals Home,Away Team,Away Goals,home_possessions,...,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red,links
0,28th May 2023,4:30pm,Emirates Stadium,h,"60,095",2,5,13,0,51.0,...,52.2,0,3,8,11,0,0,0,0,https://www.skysports.com/football/arsenal-vs-...
1,28th May 2023,4:30pm,Villa Park,h,"42,212",7,2,6,1,40.3,...,47.8,3,3,15,16,4,4,0,0,https://www.skysports.com/football/aston-villa...
2,28th May 2023,4:30pm,Gtech Community Stadium,h,"17,120",9,1,1,0,34.4,...,50.0,2,3,12,8,4,0,0,0,https://www.skysports.com/football/brentford-v...
3,28th May 2023,4:30pm,Stamford Bridge,d,"40,130",12,1,4,1,64.4,...,45.5,3,5,9,11,0,0,0,0,https://www.skysports.com/football/chelsea-vs-...
4,28th May 2023,4:30pm,Selhurst Park,d,"25,198",11,1,16,1,66.0,...,41.7,3,2,9,13,0,2,0,0,https://www.skysports.com/football/crystal-pal...

In [3]:
dataset.describe()

,Home Team,Goals Home,Away Team,Away Goals,home_possessions,away_possessions,home_shots,away_shots,home_on,away_on,...,home_duels,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,...,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000
mean,11.450000,1.502632,11.450000,1.290351,50.816754,49.205965,13.558772,11.474561,4.715789,4.039474,...,50.753772,49.342632,2.728070,3.178070,10.620175,10.567544,1.587719,1.722807,0.051754,0.053509
std,6.815784,1.359450,6.815784,1.233457,12.896181,12.899495,5.615658,5.048515,2.564688,2.359525,...,10.757576,10.777668,1.856035,1.978562,3.415676,3.560070,1.216014,1.279406,0.233210,0.236554
min,1.000000,0.000000,1.000000,0.000000,17.900000,17.600000,1.000000,1.000000,0.000000,0.000000,...,10.000000,10.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.750000,0.750000,5.750000,0.000000,40.900000,39.100000,9.000000,8.000000,3.000000,2.000000,...,43.800000,42.300000,1.000000,2.000000,8.000000,8.000000,1.000000,1.000000,0.000000,0.000000
50%,11.000000,1.000000,11.000000,1.000000,50.850000,49.200000,13.000000,11.000000,5.000000,4.000000,...,50.000000,50.000000,2.000000,3.000000,10.000000,10.000000,1.000000,2.000000,0.000000,0.000000
75%,17.250000,2.000000,17.250000,2.000000,60.900000,59.125000,17.000000,15.000000,6.000000,5.000000,...,57.700000,56.350000,4.000000,4.000000,13.000000,13.000000,2.000000,3.000000,0.000000,0.000000
max,25.000000,9.000000,25.000000,7.000000,82.400000,82.100000,33.000000,31.000000,15.000000,14.000000,...,90.000000,90.000000,10.000000,11.000000,23.000000,25.000000,6.000000,7.000000,2.000000,2.000000

In [ ]:
dataset.columns

Index(['date', 'clock', 'stadium', 'class', 'attendance', 'Home Team',
       'Goals Home', 'Away Team', 'Away Goals', 'home_possessions',
       'away_possessions', 'home_shots', 'away_shots', 'home_on', 'away_on',
       'home_off', 'away_off', 'home_blocked', 'away_blocked', 'home_pass',
       'away_pass', 'home_chances', 'away_chances', 'home_corners',
       'away_corners', 'home_offside', 'away_offside', 'home_tackles',
       'away_tackles', 'home_duels', 'away_duels', 'home_saves', 'away_saves',
       'home_fouls', 'away_fouls', 'home_yellow', 'away_yellow', 'home_red',
       'away_red', 'links'],
      dtype='object')

In [22]:
X = dataset.drop(columns=['links', 'class', 'Goals Home', 'Away Goals'], axis=1)
y = pd.DataFrame((dataset['class'] == 'h') * 1)
categorical_X = [cname for cname in X.columns
                 if X[cname].dtype == 'object'
                 and len(X[cname].unique()) < 5]
numerical_X = [cname for cname in X.columns
               if X[cname].dtype in ['float64', 'int64']
               and len(X[cname].unique()) > 5]
print(categorical_X, numerical_X, y)

[] ['Home Team', 'Away Team', 'home_possessions', 'away_possessions', 'home_shots', 'away_shots', 'home_on', 'away_on', 'home_off', 'away_off', 'home_blocked', 'away_blocked', 'home_pass', 'away_pass', 'home_chances', 'away_chances', 'home_corners', 'away_corners', 'home_offside', 'away_offside', 'home_tackles', 'away_tackles', 'home_duels', 'away_duels', 'home_saves', 'away_saves', 'home_fouls', 'away_fouls', 'home_yellow', 'away_yellow']       class
0         1
1         1
2         1
3         0
4         0
...     ...
1135      0
1136      0
1137      1
1138      1
1139      0

[1140 rows x 1 columns]

We see that there are no categorical variables (well we can use time or team as a categorical variable but it would be unnecessarily complex). I also removed away and home goals as it leads to test train contamination. We create a simple tree model.

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X = X[numerical_X]
X_train, X_val, y_train, y_val = train_test_split(X, y)
pipe = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('tree', RandomForestClassifier())
])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_val)
print(accuracy_score(y_val, y_pred))

/usr/lib/python3/dist-packages/sklearn/base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.7087719298245614

our model has a 71% accuracy (well, at least it doesn't know the future like in app.ipynb). now we use the eli5 library to see which are the most significant variables.

In [25]:
import eli5.sklearn
from eli5.sklearn import PermutationImportance

ModuleNotFoundError: No module named 'eli5'

In [ ]:
perm = PermutationImportance(pipe_ovo, random_state=1).fit(X_val, y_val)
eli5.show_weights(perm, )